name: BB Services CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build
      run: sbt clean compile dist
    - name: Docker Build
      run: docker build -t $DOCKER_USER/bullish-breakouts:latest ./
    - name: Docker push
      run: docker push $DOCKER_USER/bullish-breakouts:latest
