name: BB Services CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set environment variables
      run: |
          echo ${{ secrets.DOCKER_USER }} > DOCKER_USER
          echo ${{ secrets.DOCKER_PASS }} > DOCKER_PASS
    - name: Docker login
      run: docker login -u $(cat DOCKER_USER) --password-stdin $(cat DOCKER_PASS)
    - name: Build
      run: sbt clean compile dist
    - name: Docker Build
      run: docker build -t $(cat DOCKER_USER)/bullish-breakouts:latest ./
    - name: Docker push
      run: docker push $(cat DOCKER_USER)/bullish-breakouts:latest
